# Generated by Django 5.1.5 on 2025-02-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('user_allocated_money', 'Add money to department'), ('admin_allocated_money', 'Add money to Admin')], max_length=50),
        ),
    ]
